-- Imported manufacturer official-homepage boundary audit.
-- Mercedes-Benz, Audi, Volvo, Honda, and Nissan rows are confirmed only at
-- model-lineup/archive status level here. Generated powertrain placeholders
-- must not remain selectable until official model-year spec sheets are audited.

with audited_model_ids(id, source_name, source_url) as (
  values
    ('model-benz-065-a-class', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-066-c-class', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-067-e-class', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-068-s-class', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-069-gla', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-070-glc', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-071-gle', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-072-gls', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-073-eqa', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-074-eqb', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-075-eqe', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-076-eqs', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-s-class-long-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-maybach-s-class-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-eqe-suv-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-maybach-eqs-suv-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-glb-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-glc-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-gle-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-maybach-gls-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-g-class-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-cla-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-cle-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-amg-gt-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-amg-gt-4door-coupe-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-cle-cabriolet-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-sl-roadster-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-benz-maybach-sl-monogram-kr', 'Mercedes-Benz Korea official model overview boundary audit', 'https://www.mercedes-benz.co.kr/passengercars/models.html'),
    ('model-audi-077-a3', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-078-a4', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-079-a5', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-080-a6', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-081-a7', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-082-a8', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-083-q3', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-084-q5', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-085-q7', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-086-q8', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-087-e-tron', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-088-q4-e-tron', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-e-tron-gt-kr', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-a6-e-tron-kr', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-audi-q6-e-tron-kr', 'Audi Korea official model overview boundary audit', 'https://www.audi.co.kr/ko/models/'),
    ('model-volvo-124-s60', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-125-s90', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-126-xc40', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-127-xc60', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-128-xc90', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-129-c40', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-130-ex30', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-131-ex90', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-volvo-ex30-cross-country-kr', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/cars/ex30-electric/'),
    ('model-volvo-es90-kr', 'Volvo Cars Korea official ES90 preorder boundary audit', 'https://www.volvocars.com/kr/news/culture/20260611-Volvo-Car-Opens-ES90-Pre-Orders/'),
    ('model-volvo-v60-cross-country-kr', 'Volvo Cars Korea official model lineup boundary audit', 'https://www.volvocars.com/kr/'),
    ('model-honda-109-kr', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-honda-110-kr', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-honda-111-cr-v', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-honda-112-hr-v', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-honda-113-kr', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-honda-114-kr', 'Honda Korea official showroom boundary audit', 'https://auto.hondakorea.co.kr/main/'),
    ('model-nissan-115-kr', 'Nissan Korea official withdrawal/archive boundary audit', 'https://www.nissan.co.kr/news_and_events/2002_news_b1.html'),
    ('model-nissan-116-kr', 'Nissan Korea official withdrawal/archive boundary audit', 'https://www.nissan.co.kr/news_and_events/2002_news_b1.html'),
    ('model-nissan-117-kr', 'Nissan Korea official withdrawal/archive boundary audit', 'https://www.nissan.co.kr/news_and_events/2002_news_b1.html'),
    ('model-nissan-118-kr', 'Nissan Korea official withdrawal/archive boundary audit', 'https://www.nissan.co.kr/experience-nissan-im/news_and_events/190318.html'),
    ('model-nissan-119-kr', 'Nissan Korea official withdrawal/archive boundary audit', 'https://www.nissan.co.kr/news_and_events/2002_news_b1.html')
)
update public.vehicle_variants vv
set
  trim_name = '공식 제원 검수 대기',
  engine_name = 'Pending official specification review',
  displacement_cc = null,
  battery_kwh = null,
  drivetrain = '검수 대기',
  transmission = '검수 대기',
  official_efficiency = null,
  is_verified = false,
  source_status = 'pending_review',
  source_name = ami.source_name,
  source_url = ami.source_url,
  source_file_name = null,
  last_verified_at = '2026-06-13',
  confidence_score = 0.10,
  is_selectable = false,
  is_deprecated = false
from public.vehicle_model_years vmy
join audited_model_ids ami on ami.id = vmy.model_id
where vv.model_year_id = vmy.id;

with audited_model_ids(id) as (
  values
    ('model-benz-065-a-class'), ('model-benz-066-c-class'),
    ('model-benz-067-e-class'), ('model-benz-068-s-class'),
    ('model-benz-069-gla'), ('model-benz-070-glc'),
    ('model-benz-071-gle'), ('model-benz-072-gls'),
    ('model-benz-073-eqa'), ('model-benz-074-eqb'),
    ('model-benz-075-eqe'), ('model-benz-076-eqs'),
    ('model-benz-s-class-long-kr'), ('model-benz-maybach-s-class-kr'),
    ('model-benz-eqe-suv-kr'), ('model-benz-maybach-eqs-suv-kr'),
    ('model-benz-glb-kr'), ('model-benz-glc-coupe-kr'),
    ('model-benz-gle-coupe-kr'), ('model-benz-maybach-gls-kr'),
    ('model-benz-g-class-kr'), ('model-benz-cla-coupe-kr'),
    ('model-benz-cle-coupe-kr'), ('model-benz-amg-gt-coupe-kr'),
    ('model-benz-amg-gt-4door-coupe-kr'), ('model-benz-cle-cabriolet-kr'),
    ('model-benz-sl-roadster-kr'), ('model-benz-maybach-sl-monogram-kr'),
    ('model-audi-077-a3'), ('model-audi-078-a4'),
    ('model-audi-079-a5'), ('model-audi-080-a6'),
    ('model-audi-081-a7'), ('model-audi-082-a8'),
    ('model-audi-083-q3'), ('model-audi-084-q5'),
    ('model-audi-085-q7'), ('model-audi-086-q8'),
    ('model-audi-087-e-tron'), ('model-audi-088-q4-e-tron'),
    ('model-audi-e-tron-gt-kr'), ('model-audi-a6-e-tron-kr'),
    ('model-audi-q6-e-tron-kr'),
    ('model-volvo-124-s60'), ('model-volvo-125-s90'),
    ('model-volvo-126-xc40'), ('model-volvo-127-xc60'),
    ('model-volvo-128-xc90'), ('model-volvo-129-c40'),
    ('model-volvo-130-ex30'), ('model-volvo-131-ex90'),
    ('model-volvo-ex30-cross-country-kr'), ('model-volvo-es90-kr'),
    ('model-volvo-v60-cross-country-kr'),
    ('model-honda-109-kr'), ('model-honda-110-kr'),
    ('model-honda-111-cr-v'), ('model-honda-112-hr-v'),
    ('model-honda-113-kr'), ('model-honda-114-kr'),
    ('model-nissan-115-kr'), ('model-nissan-116-kr'),
    ('model-nissan-117-kr'), ('model-nissan-118-kr'),
    ('model-nissan-119-kr')
)
delete from public.vehicle_powertrain_sources vps
using public.vehicle_variants vv,
  public.vehicle_model_years vmy,
  audited_model_ids ami
where vps.powertrain_id = vv.id
  and vv.model_year_id = vmy.id
  and vmy.model_id = ami.id
  and vv.source_status not in ('verified_official', 'verified_admin');
