-- Jeep Wrangler Trail Hunt official card audit.
-- Jeep Korea exposes Trail Hunt as a Wrangler edition/card, so it is kept as a
-- Wrangler trim/powertrain candidate instead of a standalone vehicle_model.
-- Row-level domestic specifications are not verified yet; rows stay pending,
-- non-selectable, and free of numeric specs.

with jeep_cards (
  id,
  model_year_id,
  generation_id,
  trim_name,
  engine_name,
  fuel_type,
  efficiency_unit,
  vehicle_class,
  fuel_league,
  source_name,
  source_url,
  confidence_score,
  sort_order
) as (
  values
    (
      'variant-jeep-152-kr-2026-gasoline',
      'year-jeep-152-kr-2026',
      'generation-jeep-wrangler-official-lineup',
      'Wrangler',
      'Pending official Wrangler specification review',
      '가솔린',
      'km/L',
      'SUV',
      'gasoline',
      'Jeep Korea official Wrangler page',
      'https://www.jeep.co.kr/wrangler.html',
      0.58,
      10
    ),
    (
      'variant-jeep-wrangler-2026-trail-hunt-pending',
      'year-jeep-152-kr-2026',
      'generation-jeep-wrangler-official-lineup',
      'Wrangler Trail Hunt Edition',
      'Pending official Wrangler Trail Hunt Edition specification review',
      '가솔린',
      'km/L',
      'SUV',
      'gasoline',
      'Jeep Korea official Wrangler Trail Hunt Edition page',
      'https://www.jeep.co.kr/JL/wrangler/edition.html',
      0.62,
      11
    )
)
insert into public.vehicle_variants (
  id,
  model_year_id,
  generation_id,
  trim_name,
  engine_name,
  fuel_type,
  displacement_cc,
  battery_kwh,
  drivetrain,
  transmission,
  official_efficiency,
  efficiency_unit,
  vehicle_class,
  fuel_league,
  is_verified,
  source_status,
  source_name,
  source_url,
  last_verified_at,
  confidence_score,
  is_selectable,
  is_deprecated,
  sort_order
)
select
  id,
  model_year_id,
  generation_id,
  trim_name,
  engine_name,
  fuel_type,
  null::integer,
  null::numeric,
  'review pending',
  'review pending',
  null::numeric,
  efficiency_unit,
  vehicle_class,
  fuel_league,
  false,
  'pending_review',
  source_name,
  source_url,
  '2026-06-13'::date,
  confidence_score,
  false,
  false,
  sort_order
from jeep_cards
on conflict (id) do update set
  model_year_id = excluded.model_year_id,
  generation_id = excluded.generation_id,
  trim_name = excluded.trim_name,
  engine_name = excluded.engine_name,
  fuel_type = excluded.fuel_type,
  displacement_cc = excluded.displacement_cc,
  battery_kwh = excluded.battery_kwh,
  drivetrain = excluded.drivetrain,
  transmission = excluded.transmission,
  official_efficiency = excluded.official_efficiency,
  efficiency_unit = excluded.efficiency_unit,
  vehicle_class = excluded.vehicle_class,
  fuel_league = excluded.fuel_league,
  is_verified = excluded.is_verified,
  source_status = excluded.source_status,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  last_verified_at = excluded.last_verified_at,
  confidence_score = excluded.confidence_score,
  is_selectable = excluded.is_selectable,
  is_deprecated = excluded.is_deprecated,
  sort_order = excluded.sort_order;
