-- Hyundai core generation audit.
-- Adds official-source generation rows for Sonata, Grandeur, Tucson, and
-- Santa Fe. Model-year rows remain intact for backend compatibility.

insert into public.vehicle_generations (
  id,
  model_id,
  generation_order,
  generation_name_ko,
  generation_name_en,
  generation_code,
  platform_code,
  start_year,
  start_month,
  end_year,
  end_month,
  display_period,
  is_current,
  is_upcoming,
  market_region,
  source_status,
  confidence_score,
  source_name,
  source_url,
  source_file_name,
  last_verified_at,
  is_selectable,
  is_deprecated,
  updated_at
) values
  (
    'generation-hyundai-sonata-lf',
    'model-hyundai-002-kr',
    7,
    '7세대',
    'Seventh generation',
    'LF/LF PE',
    'LF',
    2014,
    null,
    2019,
    null,
    '2014~2019',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/sonata-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-sonata-dn8',
    'model-hyundai-002-kr',
    8,
    '8세대',
    'Eighth generation',
    'DN8/DN8 PE',
    'DN8',
    2019,
    null,
    null,
    null,
    '2019~현재',
    true,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/sonata-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-grandeur-hg',
    'model-hyundai-003-kr',
    5,
    '5세대',
    'Fifth generation',
    'HG',
    'HG',
    2011,
    null,
    2016,
    null,
    '2011~2016',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/grandeur-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-grandeur-ig',
    'model-hyundai-003-kr',
    6,
    '6세대',
    'Sixth generation',
    'IG/IG PE',
    'IG',
    2016,
    null,
    2022,
    null,
    '2016~2022',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/grandeur-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-grandeur-gn7',
    'model-hyundai-003-kr',
    7,
    '7세대',
    'Seventh generation',
    'GN7',
    'GN7',
    2022,
    null,
    null,
    null,
    '2022~현재',
    true,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/grandeur-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-tucson-tl',
    'model-hyundai-005-kr',
    3,
    '3세대',
    'Third generation',
    'TL/TL PE',
    'TL',
    2015,
    null,
    2020,
    null,
    '2015~2020',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/tucson-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-tucson-nx4',
    'model-hyundai-005-kr',
    4,
    '4세대',
    'Fourth generation',
    'NX4/NX4 PE',
    'NX4',
    2020,
    null,
    null,
    null,
    '2020~현재',
    true,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/tucson-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-santafe-dm',
    'model-hyundai-006-kr',
    3,
    '3세대',
    'Third generation',
    'DM/DM PE',
    'DM',
    2012,
    null,
    2018,
    null,
    '2012~2018',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/santafe-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-santafe-tm',
    'model-hyundai-006-kr',
    4,
    '4세대',
    'Fourth generation',
    'TM/TM PE',
    'TM',
    2018,
    null,
    2023,
    null,
    '2018~2023',
    false,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/santafe-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  ),
  (
    'generation-hyundai-santafe-mx5',
    'model-hyundai-006-kr',
    5,
    '5세대',
    'Fifth generation',
    'MX5',
    'MX5',
    2023,
    null,
    null,
    null,
    '2023~현재',
    true,
    false,
    'KR',
    'verified_admin',
    0.76,
    'Hyundai Motor model history and software version list',
    'https://www.hyundai.com/kr/ko/brand/brandstory/model/santafe-history',
    null,
    '2026-06-12',
    true,
    false,
    now()
  )
on conflict (id) do update set
  model_id = excluded.model_id,
  generation_order = excluded.generation_order,
  generation_name_ko = excluded.generation_name_ko,
  generation_name_en = excluded.generation_name_en,
  generation_code = excluded.generation_code,
  platform_code = excluded.platform_code,
  start_year = excluded.start_year,
  start_month = excluded.start_month,
  end_year = excluded.end_year,
  end_month = excluded.end_month,
  display_period = excluded.display_period,
  is_current = excluded.is_current,
  is_upcoming = excluded.is_upcoming,
  market_region = excluded.market_region,
  source_status = excluded.source_status,
  confidence_score = excluded.confidence_score,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_file_name = excluded.source_file_name,
  last_verified_at = excluded.last_verified_at,
  is_selectable = excluded.is_selectable,
  is_deprecated = excluded.is_deprecated,
  updated_at = now();

with generation_year_mapping (
  model_id,
  year_start,
  year_end,
  generation_id,
  production_year_label
) as (
  values
    ('model-hyundai-002-kr', 2015, 2018, 'generation-hyundai-sonata-lf', '2014~2019'),
    ('model-hyundai-002-kr', 2019, 2026, 'generation-hyundai-sonata-dn8', '2019~현재'),
    ('model-hyundai-003-kr', 2015, 2016, 'generation-hyundai-grandeur-hg', '2011~2016'),
    ('model-hyundai-003-kr', 2017, 2022, 'generation-hyundai-grandeur-ig', '2016~2022'),
    ('model-hyundai-003-kr', 2023, 2026, 'generation-hyundai-grandeur-gn7', '2022~현재'),
    ('model-hyundai-005-kr', 2015, 2019, 'generation-hyundai-tucson-tl', '2015~2020'),
    ('model-hyundai-005-kr', 2020, 2026, 'generation-hyundai-tucson-nx4', '2020~현재'),
    ('model-hyundai-006-kr', 2015, 2017, 'generation-hyundai-santafe-dm', '2012~2018'),
    ('model-hyundai-006-kr', 2018, 2022, 'generation-hyundai-santafe-tm', '2018~2023'),
    ('model-hyundai-006-kr', 2023, 2026, 'generation-hyundai-santafe-mx5', '2023~현재')
)
update public.vehicle_model_years vmy
set
  generation_id = gym.generation_id,
  production_year_label = gym.production_year_label
from generation_year_mapping gym
where vmy.model_id = gym.model_id
  and vmy.year between gym.year_start and gym.year_end;

insert into public.vehicle_generation_years (
  generation_id,
  model_year_id,
  year
)
select generation_id, id, year
from public.vehicle_model_years
where generation_id in (
  'generation-hyundai-sonata-lf',
  'generation-hyundai-sonata-dn8',
  'generation-hyundai-grandeur-hg',
  'generation-hyundai-grandeur-ig',
  'generation-hyundai-grandeur-gn7',
  'generation-hyundai-tucson-tl',
  'generation-hyundai-tucson-nx4',
  'generation-hyundai-santafe-dm',
  'generation-hyundai-santafe-tm',
  'generation-hyundai-santafe-mx5'
)
on conflict (generation_id, model_year_id) do nothing;

update public.vehicle_variants vv
set generation_id = vmy.generation_id
from public.vehicle_model_years vmy
where vv.model_year_id = vmy.id
  and vmy.generation_id in (
    'generation-hyundai-sonata-lf',
    'generation-hyundai-sonata-dn8',
    'generation-hyundai-grandeur-hg',
    'generation-hyundai-grandeur-ig',
    'generation-hyundai-grandeur-gn7',
    'generation-hyundai-tucson-tl',
    'generation-hyundai-tucson-nx4',
    'generation-hyundai-santafe-dm',
    'generation-hyundai-santafe-tm',
    'generation-hyundai-santafe-mx5'
  );
