-- Remaining imported/manufacturer lineup generation audit.
-- Connects every still-unlinked seed model to a conservative official-lineup
-- generation row. These rows intentionally stay pending_review until model
-- generation codes and domestic spec sheets are audited model-by-model.

with remaining_generations (
  id,
  model_id,
  source_name,
  source_url,
  confidence_score
) as (
  values
    ('generation-volkswagen-golf-official-lineup', 'model-volkswagen-089-kr', 'Volkswagen Korea official model lineup', 'https://www.volkswagen.co.kr/ko.html', 0.56),
    ('generation-volkswagen-jetta-official-lineup', 'model-volkswagen-090-kr', 'Volkswagen Korea official model/news pages', 'https://www.volkswagen.co.kr/ko/promotion_news/news/2021/2021-03-05.html', 0.52),
    ('generation-volkswagen-passat-official-lineup', 'model-volkswagen-091-kr', 'Volkswagen Korea official model/news pages', 'https://www.volkswagen.co.kr/ko/promotion_news/news/2021/2021-03-05.html', 0.52),
    ('generation-volkswagen-tiguan-official-lineup', 'model-volkswagen-092-kr', 'Volkswagen Korea official model/news pages', 'https://www.volkswagen.co.kr/ko/promotion_news/news/news-2022.html', 0.54),
    ('generation-volkswagen-touareg-official-lineup', 'model-volkswagen-093-kr', 'Volkswagen Korea official model lineup', 'https://www.volkswagen.co.kr/ko.html', 0.56),
    ('generation-volkswagen-id4-official-lineup', 'model-volkswagen-094-id-4', 'Volkswagen Korea official model lineup', 'https://www.volkswagen.co.kr/ko.html', 0.56),
    ('generation-volkswagen-arteon-official-lineup', 'model-volkswagen-095-kr', 'Volkswagen Korea official model/news pages', 'https://www.volkswagen.co.kr/ko/promotion_news/news/2021/2021-03-05.html', 0.52),
    ('generation-toyota-prius-official-lineup', 'model-toyota-096-kr', 'Toyota Korea official model lineup', 'https://www.toyota.co.kr/', 0.56),
    ('generation-toyota-camry-official-lineup', 'model-toyota-097-kr', 'Toyota Korea official model lineup', 'https://www.toyota.co.kr/', 0.56),
    ('generation-toyota-rav4-official-lineup', 'model-toyota-098-4', 'Toyota Korea official model lineup', 'https://www.toyota.co.kr/', 0.56),
    ('generation-toyota-highlander-official-lineup', 'model-toyota-099-kr', 'Toyota Korea official model lineup', 'https://www.toyota.co.kr/', 0.56),
    ('generation-toyota-sienna-official-lineup', 'model-toyota-100-kr', 'Toyota Korea official owner/test-drive pages', 'https://www.toyota.co.kr/test-drive/', 0.56),
    ('generation-toyota-crown-official-lineup', 'model-toyota-101-kr', 'Toyota Korea official model lineup', 'https://www.toyota.co.kr/', 0.56),
    ('generation-toyota-gr86-official-lineup', 'model-toyota-102-gr86', 'Toyota Korea official owner/test-drive pages', 'https://www.toyota.co.kr/test-drive/', 0.56),
    ('generation-lexus-es-official-lineup', 'model-lexus-103-es', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-lexus-ls-official-lineup', 'model-lexus-104-ls', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-lexus-nx-official-lineup', 'model-lexus-105-nx', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-lexus-rx-official-lineup', 'model-lexus-106-rx', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-lexus-ux-official-lineup', 'model-lexus-107-ux', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-lexus-rz-official-lineup', 'model-lexus-108-rz', 'Lexus Korea official electrified lineup', 'https://www.lexus.co.kr/contents/2022-lexus-electrified/electrified', 0.56),
    ('generation-honda-civic-official-lineup', 'model-honda-109-kr', 'Honda official automobile lineup', 'https://automobiles.honda.com/', 0.50),
    ('generation-honda-accord-official-lineup', 'model-honda-110-kr', 'Honda Korea official online showroom', 'https://auto.hondakorea.co.kr/main/', 0.56),
    ('generation-honda-cr-v-official-lineup', 'model-honda-111-cr-v', 'Honda Korea official online showroom', 'https://auto.hondakorea.co.kr/main/', 0.56),
    ('generation-honda-hr-v-official-lineup', 'model-honda-112-hr-v', 'Honda official automobile lineup', 'https://automobiles.honda.com/', 0.50),
    ('generation-honda-pilot-official-lineup', 'model-honda-113-kr', 'Honda Korea official online showroom', 'https://auto.hondakorea.co.kr/main/', 0.56),
    ('generation-honda-odyssey-official-lineup', 'model-honda-114-kr', 'Honda Korea official online showroom', 'https://auto.hondakorea.co.kr/main/', 0.56),
    ('generation-nissan-altima-official-lineup', 'model-nissan-115-kr', 'Nissan Korea official news and service archive', 'https://www.nissan.co.kr/experience-nissan-im/news_and_events.html', 0.50),
    ('generation-nissan-maxima-official-lineup', 'model-nissan-116-kr', 'Nissan Korea official news and service archive', 'https://www.nissan.co.kr/', 0.48),
    ('generation-nissan-rogue-official-lineup', 'model-nissan-117-kr', 'Nissan Korea official news and service archive', 'https://www.nissan.co.kr/', 0.48),
    ('generation-nissan-leaf-official-lineup', 'model-nissan-118-kr', 'Nissan Korea official Leaf launch/news pages', 'https://www.nissan.co.kr/experience-nissan-im/news_and_events/190318.html', 0.58),
    ('generation-nissan-ariya-official-lineup', 'model-nissan-119-kr', 'Nissan official Ariya model page', 'https://www.nissanusa.com/vehicles/discontinued/ariya.html', 0.48),
    ('generation-tesla-model3-official-lineup', 'model-tesla-120-model-3', 'Tesla Korea official Model 3 page', 'https://www.tesla.com/ko_kr/model3', 0.64),
    ('generation-tesla-modely-official-lineup', 'model-tesla-121-model-y', 'Tesla Korea official Model Y page', 'https://www.tesla.com/ko_kr/modely', 0.64),
    ('generation-tesla-models-official-lineup', 'model-tesla-122-model-s', 'Tesla Korea official Model S page', 'https://www.tesla.com/ko_kr/models', 0.60),
    ('generation-tesla-modelx-official-lineup', 'model-tesla-123-model-x', 'Tesla Korea official Model X page', 'https://www.tesla.com/ko_kr/modelx', 0.60),
    ('generation-porsche-911-official-lineup', 'model-porsche-132-911', 'Porsche Korea official model overview', 'https://www.porsche.com/korea/ko/models/', 0.56),
    ('generation-porsche-boxster-official-lineup', 'model-porsche-133-kr', 'Porsche Korea official model overview', 'https://www.porsche.com/korea/ko/models/', 0.54),
    ('generation-porsche-cayman-official-lineup', 'model-porsche-134-kr', 'Porsche Korea official model overview', 'https://www.porsche.com/korea/ko/models/', 0.54),
    ('generation-porsche-panamera-official-lineup', 'model-porsche-135-kr', 'Porsche Korea official Panamera page', 'https://www.porsche.com/korea/ko/models/panamera/', 0.56),
    ('generation-porsche-macan-official-lineup', 'model-porsche-136-kr', 'Porsche Korea official model overview', 'https://www.porsche.com/korea/ko/models/', 0.56),
    ('generation-porsche-cayenne-official-lineup', 'model-porsche-137-kr', 'Porsche Korea official Cayenne page', 'https://www.porsche.com/korea/ko/models/Cayenne/', 0.56),
    ('generation-porsche-taycan-official-lineup', 'model-porsche-138-kr', 'Porsche Korea official Taycan page', 'https://www.porsche.com/korea/ko/models/taycan/', 0.56),
    ('generation-mini-hatch-official-lineup', 'model-mini-139-kr', 'MINI Korea official model range', 'https://www.mini.co.kr/ko_KR/home.html', 0.56),
    ('generation-mini-countryman-official-lineup', 'model-mini-140-kr', 'MINI Korea official model range', 'https://www.mini.co.kr/ko_KR/home.html', 0.56),
    ('generation-mini-clubman-official-lineup', 'model-mini-141-kr', 'MINI Korea official model range/archive', 'https://www.mini.co.kr/ko_KR/home/faqs.html', 0.52),
    ('generation-mini-cooper-se-official-lineup', 'model-mini-142-se', 'MINI Korea official model range', 'https://www.mini.co.kr/ko_KR/home.html', 0.56),
    ('generation-mini-convertible-official-lineup', 'model-mini-143-kr', 'MINI Korea official model range', 'https://www.mini.co.kr/ko_KR/home.html', 0.56),
    ('generation-peugeot-208-official-lineup', 'model-peugeot-144-208', 'Peugeot Korea official model lineup', 'https://www.epeugeot.co.kr/', 0.52),
    ('generation-peugeot-308-official-lineup', 'model-peugeot-145-308', 'Peugeot Korea official model lineup', 'https://www.epeugeot.co.kr/', 0.56),
    ('generation-peugeot-2008-official-lineup', 'model-peugeot-146-2008', 'Peugeot Korea official model lineup', 'https://www.epeugeot.co.kr/', 0.52),
    ('generation-peugeot-3008-official-lineup', 'model-peugeot-147-3008', 'Peugeot Korea official model lineup', 'https://www.epeugeot.co.kr/', 0.56),
    ('generation-peugeot-5008-official-lineup', 'model-peugeot-148-5008', 'Peugeot Korea official model lineup', 'https://www.epeugeot.co.kr/', 0.56),
    ('generation-jeep-renegade-official-lineup', 'model-jeep-149-kr', 'Jeep Korea official promotion/archive pages', 'https://www.jeep.co.kr/promotion.html', 0.50),
    ('generation-jeep-compass-official-lineup', 'model-jeep-150-kr', 'Jeep Korea official Compass page', 'https://www.jeep.co.kr/compass.html', 0.54),
    ('generation-jeep-cherokee-official-lineup', 'model-jeep-151-kr', 'Jeep Korea official promotion/archive pages', 'https://www.jeep.co.kr/promotion.html', 0.50),
    ('generation-jeep-wrangler-official-lineup', 'model-jeep-152-kr', 'Jeep Korea official model lineup', 'https://www.jeep.co.kr/', 0.56),
    ('generation-jeep-grand-cherokee-official-lineup', 'model-jeep-153-kr', 'Jeep Korea official model lineup', 'https://www.jeep.co.kr/', 0.56),
    ('generation-landrover-defender-official-lineup', 'model-landrover-154-kr', 'Land Rover Korea official model pages', 'https://www.landroverkorea.co.kr/defender/index.html', 0.56),
    ('generation-landrover-discovery-official-lineup', 'model-landrover-155-kr', 'Land Rover Korea official model pages', 'https://www.landroverkorea.co.kr/discovery/discovery/index.html', 0.56),
    ('generation-landrover-range-rover-official-lineup', 'model-landrover-156-kr', 'Range Rover Korea official model page', 'https://www.rangerover.com/ko-kr/index.html', 0.56),
    ('generation-landrover-range-rover-sport-official-lineup', 'model-landrover-157-kr', 'Range Rover Korea official model page', 'https://www.rangerover.com/ko-kr/range-rover-sport/index.html', 0.56),
    ('generation-landrover-range-rover-evoque-official-lineup', 'model-landrover-158-kr', 'Range Rover Korea official Evoque page', 'https://www.landroverkorea.co.kr/range-rover/range-rover-evoque/index.html', 0.56),
    ('generation-polestar-2-official-lineup', 'model-polestar-159-polestar-2', 'Polestar Korea official model pages', 'https://www.polestar.com/kr/', 0.56),
    ('generation-polestar-3-official-lineup', 'model-polestar-160-polestar-3', 'Polestar Korea official Polestar 3 page', 'https://www.polestar.com/kr/polestar-3/', 0.56),
    ('generation-polestar-4-official-lineup', 'model-polestar-161-polestar-4', 'Polestar Korea official Polestar 4 page', 'https://www.polestar.com/kr/polestar-4-models/polestar-4-coupe/', 0.56)
)
insert into public.vehicle_generations (
  id,
  model_id,
  generation_order,
  generation_name_ko,
  generation_name_en,
  generation_code,
  platform_code,
  start_year,
  start_month,
  end_year,
  end_month,
  display_period,
  is_current,
  is_upcoming,
  market_region,
  source_status,
  confidence_score,
  source_name,
  source_url,
  source_file_name,
  last_verified_at,
  is_selectable,
  is_deprecated,
  updated_at
)
select
  id,
  model_id,
  1,
  '공식 라인업',
  'Official lineup',
  '',
  '',
  2015,
  null,
  null,
  null,
  '2015~현재',
  true,
  false,
  'KR',
  'pending_review',
  confidence_score,
  source_name,
  source_url,
  null,
  '2026-06-13',
  true,
  false,
  now()
from remaining_generations
on conflict (id) do update set
  model_id = excluded.model_id,
  generation_order = excluded.generation_order,
  generation_name_ko = excluded.generation_name_ko,
  generation_name_en = excluded.generation_name_en,
  generation_code = excluded.generation_code,
  platform_code = excluded.platform_code,
  start_year = excluded.start_year,
  start_month = excluded.start_month,
  end_year = excluded.end_year,
  end_month = excluded.end_month,
  display_period = excluded.display_period,
  is_current = excluded.is_current,
  is_upcoming = excluded.is_upcoming,
  market_region = excluded.market_region,
  source_status = excluded.source_status,
  confidence_score = excluded.confidence_score,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_file_name = excluded.source_file_name,
  last_verified_at = excluded.last_verified_at,
  is_selectable = excluded.is_selectable,
  is_deprecated = excluded.is_deprecated,
  updated_at = now();

with remaining_generations (generation_id, model_id) as (
  values
    ('generation-volkswagen-golf-official-lineup', 'model-volkswagen-089-kr'),
    ('generation-volkswagen-jetta-official-lineup', 'model-volkswagen-090-kr'),
    ('generation-volkswagen-passat-official-lineup', 'model-volkswagen-091-kr'),
    ('generation-volkswagen-tiguan-official-lineup', 'model-volkswagen-092-kr'),
    ('generation-volkswagen-touareg-official-lineup', 'model-volkswagen-093-kr'),
    ('generation-volkswagen-id4-official-lineup', 'model-volkswagen-094-id-4'),
    ('generation-volkswagen-arteon-official-lineup', 'model-volkswagen-095-kr'),
    ('generation-toyota-prius-official-lineup', 'model-toyota-096-kr'),
    ('generation-toyota-camry-official-lineup', 'model-toyota-097-kr'),
    ('generation-toyota-rav4-official-lineup', 'model-toyota-098-4'),
    ('generation-toyota-highlander-official-lineup', 'model-toyota-099-kr'),
    ('generation-toyota-sienna-official-lineup', 'model-toyota-100-kr'),
    ('generation-toyota-crown-official-lineup', 'model-toyota-101-kr'),
    ('generation-toyota-gr86-official-lineup', 'model-toyota-102-gr86'),
    ('generation-lexus-es-official-lineup', 'model-lexus-103-es'),
    ('generation-lexus-ls-official-lineup', 'model-lexus-104-ls'),
    ('generation-lexus-nx-official-lineup', 'model-lexus-105-nx'),
    ('generation-lexus-rx-official-lineup', 'model-lexus-106-rx'),
    ('generation-lexus-ux-official-lineup', 'model-lexus-107-ux'),
    ('generation-lexus-rz-official-lineup', 'model-lexus-108-rz'),
    ('generation-honda-civic-official-lineup', 'model-honda-109-kr'),
    ('generation-honda-accord-official-lineup', 'model-honda-110-kr'),
    ('generation-honda-cr-v-official-lineup', 'model-honda-111-cr-v'),
    ('generation-honda-hr-v-official-lineup', 'model-honda-112-hr-v'),
    ('generation-honda-pilot-official-lineup', 'model-honda-113-kr'),
    ('generation-honda-odyssey-official-lineup', 'model-honda-114-kr'),
    ('generation-nissan-altima-official-lineup', 'model-nissan-115-kr'),
    ('generation-nissan-maxima-official-lineup', 'model-nissan-116-kr'),
    ('generation-nissan-rogue-official-lineup', 'model-nissan-117-kr'),
    ('generation-nissan-leaf-official-lineup', 'model-nissan-118-kr'),
    ('generation-nissan-ariya-official-lineup', 'model-nissan-119-kr'),
    ('generation-tesla-model3-official-lineup', 'model-tesla-120-model-3'),
    ('generation-tesla-modely-official-lineup', 'model-tesla-121-model-y'),
    ('generation-tesla-models-official-lineup', 'model-tesla-122-model-s'),
    ('generation-tesla-modelx-official-lineup', 'model-tesla-123-model-x'),
    ('generation-porsche-911-official-lineup', 'model-porsche-132-911'),
    ('generation-porsche-boxster-official-lineup', 'model-porsche-133-kr'),
    ('generation-porsche-cayman-official-lineup', 'model-porsche-134-kr'),
    ('generation-porsche-panamera-official-lineup', 'model-porsche-135-kr'),
    ('generation-porsche-macan-official-lineup', 'model-porsche-136-kr'),
    ('generation-porsche-cayenne-official-lineup', 'model-porsche-137-kr'),
    ('generation-porsche-taycan-official-lineup', 'model-porsche-138-kr'),
    ('generation-mini-hatch-official-lineup', 'model-mini-139-kr'),
    ('generation-mini-countryman-official-lineup', 'model-mini-140-kr'),
    ('generation-mini-clubman-official-lineup', 'model-mini-141-kr'),
    ('generation-mini-cooper-se-official-lineup', 'model-mini-142-se'),
    ('generation-mini-convertible-official-lineup', 'model-mini-143-kr'),
    ('generation-peugeot-208-official-lineup', 'model-peugeot-144-208'),
    ('generation-peugeot-308-official-lineup', 'model-peugeot-145-308'),
    ('generation-peugeot-2008-official-lineup', 'model-peugeot-146-2008'),
    ('generation-peugeot-3008-official-lineup', 'model-peugeot-147-3008'),
    ('generation-peugeot-5008-official-lineup', 'model-peugeot-148-5008'),
    ('generation-jeep-renegade-official-lineup', 'model-jeep-149-kr'),
    ('generation-jeep-compass-official-lineup', 'model-jeep-150-kr'),
    ('generation-jeep-cherokee-official-lineup', 'model-jeep-151-kr'),
    ('generation-jeep-wrangler-official-lineup', 'model-jeep-152-kr'),
    ('generation-jeep-grand-cherokee-official-lineup', 'model-jeep-153-kr'),
    ('generation-landrover-defender-official-lineup', 'model-landrover-154-kr'),
    ('generation-landrover-discovery-official-lineup', 'model-landrover-155-kr'),
    ('generation-landrover-range-rover-official-lineup', 'model-landrover-156-kr'),
    ('generation-landrover-range-rover-sport-official-lineup', 'model-landrover-157-kr'),
    ('generation-landrover-range-rover-evoque-official-lineup', 'model-landrover-158-kr'),
    ('generation-polestar-2-official-lineup', 'model-polestar-159-polestar-2'),
    ('generation-polestar-3-official-lineup', 'model-polestar-160-polestar-3'),
    ('generation-polestar-4-official-lineup', 'model-polestar-161-polestar-4')
)
update public.vehicle_model_years vmy
set
  generation_id = rg.generation_id,
  production_year_label = '2015~현재'
from remaining_generations rg
where vmy.model_id = rg.model_id
  and vmy.year between 2015 and 2026;

insert into public.vehicle_generation_years (
  generation_id,
  model_year_id,
  year
)
select generation_id, id, year
from public.vehicle_model_years
where generation_id in (
  'generation-volkswagen-golf-official-lineup',
  'generation-volkswagen-jetta-official-lineup',
  'generation-volkswagen-passat-official-lineup',
  'generation-volkswagen-tiguan-official-lineup',
  'generation-volkswagen-touareg-official-lineup',
  'generation-volkswagen-id4-official-lineup',
  'generation-volkswagen-arteon-official-lineup',
  'generation-toyota-prius-official-lineup',
  'generation-toyota-camry-official-lineup',
  'generation-toyota-rav4-official-lineup',
  'generation-toyota-highlander-official-lineup',
  'generation-toyota-sienna-official-lineup',
  'generation-toyota-crown-official-lineup',
  'generation-toyota-gr86-official-lineup',
  'generation-lexus-es-official-lineup',
  'generation-lexus-ls-official-lineup',
  'generation-lexus-nx-official-lineup',
  'generation-lexus-rx-official-lineup',
  'generation-lexus-ux-official-lineup',
  'generation-lexus-rz-official-lineup',
  'generation-honda-civic-official-lineup',
  'generation-honda-accord-official-lineup',
  'generation-honda-cr-v-official-lineup',
  'generation-honda-hr-v-official-lineup',
  'generation-honda-pilot-official-lineup',
  'generation-honda-odyssey-official-lineup',
  'generation-nissan-altima-official-lineup',
  'generation-nissan-maxima-official-lineup',
  'generation-nissan-rogue-official-lineup',
  'generation-nissan-leaf-official-lineup',
  'generation-nissan-ariya-official-lineup',
  'generation-tesla-model3-official-lineup',
  'generation-tesla-modely-official-lineup',
  'generation-tesla-models-official-lineup',
  'generation-tesla-modelx-official-lineup',
  'generation-porsche-911-official-lineup',
  'generation-porsche-boxster-official-lineup',
  'generation-porsche-cayman-official-lineup',
  'generation-porsche-panamera-official-lineup',
  'generation-porsche-macan-official-lineup',
  'generation-porsche-cayenne-official-lineup',
  'generation-porsche-taycan-official-lineup',
  'generation-mini-hatch-official-lineup',
  'generation-mini-countryman-official-lineup',
  'generation-mini-clubman-official-lineup',
  'generation-mini-cooper-se-official-lineup',
  'generation-mini-convertible-official-lineup',
  'generation-peugeot-208-official-lineup',
  'generation-peugeot-308-official-lineup',
  'generation-peugeot-2008-official-lineup',
  'generation-peugeot-3008-official-lineup',
  'generation-peugeot-5008-official-lineup',
  'generation-jeep-renegade-official-lineup',
  'generation-jeep-compass-official-lineup',
  'generation-jeep-cherokee-official-lineup',
  'generation-jeep-wrangler-official-lineup',
  'generation-jeep-grand-cherokee-official-lineup',
  'generation-landrover-defender-official-lineup',
  'generation-landrover-discovery-official-lineup',
  'generation-landrover-range-rover-official-lineup',
  'generation-landrover-range-rover-sport-official-lineup',
  'generation-landrover-range-rover-evoque-official-lineup',
  'generation-polestar-2-official-lineup',
  'generation-polestar-3-official-lineup',
  'generation-polestar-4-official-lineup'
)
on conflict (generation_id, model_year_id) do nothing;

update public.vehicle_variants vv
set generation_id = vmy.generation_id
from public.vehicle_model_years vmy
where vv.model_year_id = vmy.id
  and vmy.generation_id in (
    'generation-volkswagen-golf-official-lineup',
    'generation-volkswagen-jetta-official-lineup',
    'generation-volkswagen-passat-official-lineup',
    'generation-volkswagen-tiguan-official-lineup',
    'generation-volkswagen-touareg-official-lineup',
    'generation-volkswagen-id4-official-lineup',
    'generation-volkswagen-arteon-official-lineup',
    'generation-toyota-prius-official-lineup',
    'generation-toyota-camry-official-lineup',
    'generation-toyota-rav4-official-lineup',
    'generation-toyota-highlander-official-lineup',
    'generation-toyota-sienna-official-lineup',
    'generation-toyota-crown-official-lineup',
    'generation-toyota-gr86-official-lineup',
    'generation-lexus-es-official-lineup',
    'generation-lexus-ls-official-lineup',
    'generation-lexus-nx-official-lineup',
    'generation-lexus-rx-official-lineup',
    'generation-lexus-ux-official-lineup',
    'generation-lexus-rz-official-lineup',
    'generation-honda-civic-official-lineup',
    'generation-honda-accord-official-lineup',
    'generation-honda-cr-v-official-lineup',
    'generation-honda-hr-v-official-lineup',
    'generation-honda-pilot-official-lineup',
    'generation-honda-odyssey-official-lineup',
    'generation-nissan-altima-official-lineup',
    'generation-nissan-maxima-official-lineup',
    'generation-nissan-rogue-official-lineup',
    'generation-nissan-leaf-official-lineup',
    'generation-nissan-ariya-official-lineup',
    'generation-tesla-model3-official-lineup',
    'generation-tesla-modely-official-lineup',
    'generation-tesla-models-official-lineup',
    'generation-tesla-modelx-official-lineup',
    'generation-porsche-911-official-lineup',
    'generation-porsche-boxster-official-lineup',
    'generation-porsche-cayman-official-lineup',
    'generation-porsche-panamera-official-lineup',
    'generation-porsche-macan-official-lineup',
    'generation-porsche-cayenne-official-lineup',
    'generation-porsche-taycan-official-lineup',
    'generation-mini-hatch-official-lineup',
    'generation-mini-countryman-official-lineup',
    'generation-mini-clubman-official-lineup',
    'generation-mini-cooper-se-official-lineup',
    'generation-mini-convertible-official-lineup',
    'generation-peugeot-208-official-lineup',
    'generation-peugeot-308-official-lineup',
    'generation-peugeot-2008-official-lineup',
    'generation-peugeot-3008-official-lineup',
    'generation-peugeot-5008-official-lineup',
    'generation-jeep-renegade-official-lineup',
    'generation-jeep-compass-official-lineup',
    'generation-jeep-cherokee-official-lineup',
    'generation-jeep-wrangler-official-lineup',
    'generation-jeep-grand-cherokee-official-lineup',
    'generation-landrover-defender-official-lineup',
    'generation-landrover-discovery-official-lineup',
    'generation-landrover-range-rover-official-lineup',
    'generation-landrover-range-rover-sport-official-lineup',
    'generation-landrover-range-rover-evoque-official-lineup',
    'generation-polestar-2-official-lineup',
    'generation-polestar-3-official-lineup',
    'generation-polestar-4-official-lineup'
  );
